### ISSUE TITLE
hdl in repository name

### ISSUE THREAD

**Issue by Fatsie** [hdl/awesome#171]
I just cloned the repository and it's name becomes Fatsie/awesome so it looses it's hdl relationship.
I think it would be better to put hdl in the repository name, like hdl/hdl-awesome

**Comment by umarcor** [comment]
There are two styles/approaches in this case:

1. Making clone/fork produce a self-explaining name, without requiring additional options. This comes at the cost of many redundant names for users cloning multiple repos.
2. Requiring users to rename explicitly, if they want to clone/fork and make it descriptive. This allows users cloning multiple repos to preserve the "namespace" as in the server.

In this organisation, we decided to use the second approach:

```sh
mkdir hdl
cd hdl
for repo in awesome constraints smoke-tests packages containers MINGW-packages Termux-packages; do
  git clone https://github.com/hdl/$repo
do
```

Then, for instance, a VSCode workspace looks like:

```json
{
	"folders": [
		{"path": "awesome"},
		{"path": "constraints"},
		{"path": "smoke-tests"},
		{"path": "packages"},
		{"path": "containers"},
		{"path": "MINGW-packages"},
		{"path": "Termux-packages"}
	],
	"settings": {}
}
```

Moreover, this is because of the philosophy of the HDL organisation. This is not a project per se; it's a set of resources for the community to gather and be aware of what other people are doing. Many of the repositories (most of them) were created elsewhere and were then moved, forked or merged into this organisation. Most of the codebase of packaging solutions is located in upstream/downstream repos. At the same time, other projects were not moved yet, or will not be moved, but are equally considered in the scope of this large low-pass filter. From this point of view 'hdl' is meaningless; just a placeholder. All users are invited to fork/submodule this or any other repo in their namespace and treat those as their own customized repos, not a "just a fork". That's also the reason for using very permissive licenses (even CC0 here).

Overall, we don't want credit or appreciation per se. We do have other many projects and orgs for that. Here, we only want to join/meet and help each other.

**Comment by Fatsie** [comment]
Thing is that if you use the Fork button on the github UI you end up with a clone repo in your own user space with awesome. So I did rename the repo now manually to [awesome-hdl](https://github.com/Fatsie/awesome-hdl)
I did not mean to imply that renaming the repo to awesome-hdl would relate it to the hdl project but to mean `an awesome list of hdl stuff`; it could also be named awesome-eda for example. Looking through github it seems that most projects include what the list is about as a suffix e.g. awesome-python, awesome-go, awesome-java, awesome-vue, ...
As this seems to have been decided I will close the issue.
