### ISSUE TITLE
Consider splitting migen and nmigen languages

### ISSUE THREAD

**Issue by mithro** [hdl/awesome#97]
Currently the migen and nmigen languages are grouped together -- this is increasingly becoming a bad grouping.

**Comment by umarcor** [comment]
Agree. However, @rodrigomelo9 and me had a hard time trying to guess what a good description/organisation would be. It is quite obvious for any visitor that there was something sad there. Copyright dates on m-labs' and whitequark's forks do overlap; and there are very slight differences in the descriptions about who supported the work.

> nMigen is based on Migen, a similar Python-based hardware description language.
> nMigen is based on Migen, a hardware description language developed by M-Labs.

> The development of nMigen has been supported by SymbioticEDA, LambdaConcept, and ChipEleven.
> The development of nMigen has been supported by M-Labs and LambdaConcept.

Hence, our first approach was: we cannot dive into each subsystem of the vast open source hardware community, if each subsystem does not make an effort for clearly communicating the important things. From a higher level perspective, we cannot allocate bandwidth for fixing "home issues". Therefore, we decided to put everything together (because all of them are coming from Migen) and wait until someone was "pissed off" enough for bringing the topic, as you did.

On the other hand, we want to be careful about having an explosion of ecosystem specific entries/items. For Chisel, SpinalHDL, Migen, etc. we might want to have all the resources gathered in a single page, where we can define subprojects, forks, derivatives etc. At the same time, LiteX is an independent item already, despite being based on Migen. This is to say everything is subject to discussion.

From a very personal point of view, I want to understand and explain what's going on. I want users of hdl/awesome to search/find an entry for Migen or nMigen and read about the existence of all nmigens, LiteX, etc. Is there a single history that we can tell? Or are there conflicting versions of what happened during the last 2-3 years? If conflicts exist and claims are unclear, I believe we should state that.

---

Assuming that we split (we created `nmigen.md`), what content should it contain? Should it be m-labs'? whitequark's? Should we use nmigen for whitequark's only and keep the m-labs' in `migen.md`?

**Comment by umarcor** [comment]
Some context: https://twitter.com/marcan42/status/1358710475748298754. I agree with marcan:

> Oh, personally, I think she should rename it just to put all this behind her and then we can all watch the "upstream" nMigen die together. But that's her decision to make, and in no way justifies what m-labs are doing here.

We'll see...

**Comment by umarcor** [comment]
- https://hdl.github.io/awesome/items/migen/
- https://hdl.github.io/awesome/items/nmigen/
